[package]
name = "dsh-desktop"
version = "0.1.1-rc.2"
edition = "2021"
license = "MIT"

[lib]
name = "dsh_desktop"
path = "src/lib.rs"

[[bin]]
name = "dsh-desktop"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = "2.9.1"

[build-dependencies]
tauri-build = "2.5.0"
